# Generated by Django 3.2.3 on 2021-06-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_food_myfoodlist_myfoodrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_logo',
            new_name='movie_logo',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='myfoodlist',
            old_name='food',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='myfoodlist',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='myfoodlist',
            old_name='addtocart',
            new_name='watch',
        ),
        migrations.RenameField(
            model_name='myfoodrating',
            old_name='food',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='myfoodrating',
            old_name='person',
            new_name='user',
        ),
    ]
