# Generated by Django 3.2.3 on 2021-06-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfoodlist',
            name='food',
        ),
        migrations.RemoveField(
            model_name='myfoodlist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='myfoodrating',
            name='food',
        ),
        migrations.RemoveField(
            model_name='myfoodrating',
            name='person',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='MyfoodList',
        ),
        migrations.DeleteModel(
            name='Myfoodrating',
        ),
    ]
